spring.application.name=gestion-pedidos

# Configuración de la base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:gestionpedidosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuración de H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuración JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Configuración del puerto del servidor
server.port=8080

# Configuración de logging
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO